// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlDOdMcY4ZPbOa0XOyXbj74xkLvW_JtKE',
    appId: '1:447697097316:web:fc2ec5770fbb1630e30571',
    messagingSenderId: '447697097316',
    projectId: 'fir-crud-5202d',
    authDomain: 'fir-crud-5202d.firebaseapp.com',
    storageBucket: 'fir-crud-5202d.firebasestorage.app',
    measurementId: 'G-ZDWJJ0NHEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBepDHHOSOhvZmrsR3wExlWyTGay8HtKQ4',
    appId: '1:447697097316:android:d9887cdae482175de30571',
    messagingSenderId: '447697097316',
    projectId: 'fir-crud-5202d',
    storageBucket: 'fir-crud-5202d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnacN6G84qRuX289ottKHC4wU3kG-25ts',
    appId: '1:447697097316:ios:f446b0e941f061f9e30571',
    messagingSenderId: '447697097316',
    projectId: 'fir-crud-5202d',
    storageBucket: 'fir-crud-5202d.firebasestorage.app',
    iosBundleId: 'com.example.firebasecrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnacN6G84qRuX289ottKHC4wU3kG-25ts',
    appId: '1:447697097316:ios:f446b0e941f061f9e30571',
    messagingSenderId: '447697097316',
    projectId: 'fir-crud-5202d',
    storageBucket: 'fir-crud-5202d.firebasestorage.app',
    iosBundleId: 'com.example.firebasecrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlDOdMcY4ZPbOa0XOyXbj74xkLvW_JtKE',
    appId: '1:447697097316:web:f191c1939fb509f0e30571',
    messagingSenderId: '447697097316',
    projectId: 'fir-crud-5202d',
    authDomain: 'fir-crud-5202d.firebaseapp.com',
    storageBucket: 'fir-crud-5202d.firebasestorage.app',
    measurementId: 'G-YKG8RNW1HS',
  );
}
